### ISSUE TITLE
Consider retiring this website in favor of the docs site

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/redprl.github.io#2]
I am starting to think that the documentation website is superior in every way! Any useful information that is on this page, we could move to the documentation website's front page, and then just replace with that entirely.

I feel that the main thing this page has going for it is the amusing slogans, but for me these are not the main point, maybe even a slight distraction.

**Comment by favonia** [comment]
I think this depends on the intended subject of the documentation website. If it is about the entire RedPRL project, then we can forget about this website. If it is about the code in `sml-redprl`, then I think it makes sense to have a separate one. That said, we can make `doc.redprl.org` the Immortal URL.

**Comment by cangiuli** [comment]
I think we should move all of what's in Overview, and possibly some of what's on redprl.org, to the main page before the Table of Contents, and then we can replace the old website.
